name: Project 360 & Executive Business Case
description: Combined application to track project status and information as well as the creation, review, and management of Executive Business Cases.
contact:
  email: gsalabs@gsa.gov
languages:
  - javascript
  - apex
permissions:
  licenses:
    - URL: http://www.usa.gov/publicdomain/label/1.0/
      name: PD
  usageType: openSource
repositoryURL: https://github.com/GSA/Project-360-Executive-Business-Case
organization: GSA
